FROM python:3.7-alpine

WORKDIR /opt/socketserver

RUN pip install -U pip && pip install pytest pytest-xdist
ADD ./socketserver.py /opt/socketserver

RUN apk update && apk add rsync

EXPOSE 8888

CMD ["python", "./socketserver.py"]
