FROM ubuntu:16.04

RUN apt-get update && apt-get install -y openssh-server python3 python3-pip && \
	    update-alternatives --install /usr/bin/python python /usr/bin/python3 1 && \
	    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 && \
	    pip install pytest pytest-xdist
RUN mkdir /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

ADD ./keys/id_rsa.pub /root/.ssh/authorized_keys

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
